// Code generated from Font Awesome Free metadata; DO NOT EDIT by hand.

package agent

// agentIcons are the icon names an agent may be given (Font Awesome Free, solid) with search keywords.
var agentIcons = []struct{ Name, Keywords string }{
	{"globe", "globe coordinates country earth global globe gps internet language"},
	{"hammer", "hammer DIY building carpentry construction equipment fix hammer hardware"},
	{"dna", "dna biologist biology chromosome dna double helix gene genetic genetics"},
	{"database", "database backend cloud data database directory information memory mysql"},
	{"brain", "brain brain cerebellum cerebrum creativity genius gray matter idea intellect"},
	{"compass", "compass adventure compass directions explore guide location magnetic map"},
	{"moon", "moon crescent crescent moon dark dark mode evening lunar moon moonlight"},
	{"magnifying-glass", "magnifying glass bigger enlarge find glass inspect inspection magnifier magnify"},
	{"terminal", "terminal cli code coding command command line command prompt console developer"},
	{"calculator", "calculator addition arithmetic calculator calculator app calculator device counting digits division"},
	{"pen-nib", "pen nib calligraphy design drawing edit handwriting modify nib pen"},
	{"house", "house abode building domicile dwelling home house living place main"},
	{"robot", "robot ai android android face artificial intelligence automate automation bot computer"},
	{"code", "code backend brackets code coding developer development frontend html"},
	{"chart-line", "chart line activity analytics chart dashboard data gain graph growth"},
	{"chart-pie", "chart pie analytics chart circle data diagram distribution graph infographic"},
	{"book", "book book diary education journal knowledge library literature manuscript"},
	{"book-open", "book open book education guide knowledge library literature manual notebook"},
	{"bell", "bell alarm alert bell buzzer call chime ding notification"},
	{"clock", "clock 4 4:00 alarm clock four four o’clock hour late"},
	{"calendar", "calendar agenda appointment calendar date day deadline event month"},
	{"envelope", "envelope contact correspondence e-mail email envelope inbox letter mail"},
	{"network-wired", "network wired cable communication computer connection data ethernet internet intranet"},
	{"wand-magic-sparkles", "wand magic sparkles enchantment fantasy magic magic wand sorcery sparkle spell trick"},
	{"wrench", "wrench adjust configuration construction equipment fix maintenance mechanic modify"},
	{"screwdriver-wrench", "screwdriver wrench adjust admin build configuration equipment fix fix-it handyman"},
	{"gear", "gear adjust cog cogwheel configuration control gear mechanical modify"},
	{"shield-halved", "shield halved achievement armor award barrier block cleric defense guard"},
	{"lock", "lock access authentication closed lock locked padlock password privacy"},
	{"key", "key access authentication credential key keyhole lock passcode password"},
	{"eye", "eye eye focus glimpse look observe peek see sight"},
	{"map", "map address atlas chart coordinates destination directions gps guide"},
	{"location-dot", "location dot address coordinates destination geotag gps location map map marker"},
	{"flask", "flask beaker chemistry experiment flask lab laboratory liquid potion"},
	{"microscope", "microscope analysis biology chemistry experiment investigation laboratory lens magnification"},
	{"graduation-cap", "graduation cap academic cap celebration ceremony college commencement diploma education"},
	{"language", "language alphabet communication dialect idiom language linguistics localization localize"},
	{"music", "music audio lyrics melody music musical note note sing song"},
	{"film", "film cinema clip film film strip footage frames media movie"},
	{"camera", "camera camera camera icon capture film image lens photo photograph"},
	{"image", "image gallery image image file landscape photo photo album photograph picture"},
	{"palette", "palette acrylic art artist palette brush color colors creativity design"},
	{"paintbrush", "paintbrush acrylic art artist brush color creativity design drawing"},
	{"cart-shopping", "cart shopping add to cart basket buy cart cart icon checkout ecommerce grocery"},
	{"tag", "tag badge coupon discount label marker price price tag sale"},
	{"dollar-sign", "dollar sign budget cash cost currency dollar dollar sign finance income"},
	{"coins", "coins cash change coins currency dime finance gold money"},
	{"wallet", "wallet billfold bills budget cash coins currency finance funds"},
	{"credit-card", "credit card billing buy card charge checkout credit card debit card finance"},
	{"truck", "truck cargo delivery delivery truck freight hauler lorry pickup shipping"},
	{"plane", "plane aircraft airplane airport arrival departure flight fly journey"},
	{"car", "car auto automobile car commute driving motorcar ride road trip"},
	{"utensils", "utensils cooking cutlery dining dinner eat eating utensils food fork"},
	{"mug-hot", "mug hot beverage cappuccino cocoa coffee cozy cup drink hot"},
	{"heart-pulse", "heart pulse cardiology ekg electrocardiogram health heart rate heartbeat lifeline medical"},
	{"dumbbell", "dumbbell dumbbell exercise fitness gym lifting muscle sports strength"},
	{"leaf", "leaf botany eco environment flora foliage garden green herb"},
	{"tree", "tree autumn bark deciduous environment evergreen foliage forest growth"},
	{"sun", "sun bright daylight daytime rays sol solar star sun"},
	{"star", "star achievement award bookmark favorite favorite item highlight important night"},
	{"bolt", "bolt bolt charge electric electricity energy flash high voltage lightning"},
	{"fire", "fire blaze burn burning campfire fire flame flame icon flame symbol"},
	{"droplet", "droplet blood drip drop droplet fluid liquid moisture oil"},
	{"cloud", "cloud atmosphere backup cloud data fog internet network online"},
	{"cube", "cube 3d block box container cube dice figure geometric"},
	{"cubes", "cubes 3d block box cube dice geometric grid package"},
	{"layer-group", "layer group arrangement category cluster collection group layers map organize"},
	{"sitemap", "sitemap directory flowchart hierarchy information architecture map navigation organization outline"},
	{"diagram-project", "diagram project chart connections diagram flowchart graph network nodes pert"},
	{"list-check", "list check approve checklist completed done mark progress project management summary"},
	{"clipboard-list", "clipboard list agenda checklist clipboard completed done finished list notes"},
	{"file-lines", "file lines document file file-text form invoice new document page paper"},
	{"folder-open", "folder open archive directory document file file folder folder folder icon folder open"},
	{"box-archive", "box archive archive backup box container delivery file folder package"},
	{"link", "link attach attachment bond chain connect connection fasten hyperlink"},
	{"rss", "rss blog broadcast channel feed headlines journal news podcast"},
	{"satellite-dish", "satellite dish SETI antenna broadcast communications dish radar receiver satellite"},
	{"tower-broadcast", "tower broadcast antenna broadcast broadcast-tower communication emergency-alert network radio reception"},
	{"headset", "headset audio call center communication customer service gamer gaming headphones headset mic"},
	{"comments", "comments chat comment communication conversation dialogue discussion feedback message"},
	{"paper-plane", "paper plane air communication delivery flight float folded paper mail message"},
	{"lightbulb", "lightbulb bright bulb concept creativity electric electricity energy idea"},
	{"puzzle-piece", "puzzle piece add-on addon block clue connect fitting game interlocking"},
	{"chess-knight", "chess knight board game checkmate chess chess match chess piece chessboard game piece horse"},
	{"seedling", "seedling agriculture eco environment farming garden green growth nature"},
	{"bug", "bug beetle bug debug defect error fix glitch insect"},
	{"user-secret", "user secret anonymous detective disguise hidden identity incognito person privacy"},
	{"binoculars", "binoculars binoculars explore glasses inspection look magnifier magnify nature"},
	{"scroll", "scroll Dungeons & Dragons announcement d&d dnd document fantasy letter manuscript"},
	{"feather", "feather bird delicate feather flight light pen plumage plume"},
	{"newspaper", "newspaper article bulletin editorial gazette headline journalism media news"},
	{"receipt", "receipt accounting bill bookkeeping check coupon expense invoice money"},
	{"scale-balanced", "scale balanced Libra balance courtroom equality equilibrium fairness judge justice"},
	{"gavel", "gavel auction court decision gavel hammer judge judge's hammer justice"},
	{"handshake", "handshake agreement alliance collaboration contract cooperation deal greeting handshake"},
	{"users", "users accounts collaboration community contacts employees group members people"},
	{"address-book", "address book address address book contact contact list contacts directory employee little black book"},
	{"bookmark", "bookmark bookmark clip favorite flag hold keep mark marker"},
	{"filter", "filter adjust criteria filter funnel narrow options refine selection"},
	{"table-columns", "table columns browser columns dashboard data grid layout organize panes"},
	{"barcode", "barcode barcode barcode-scanner code inventory label laser price product"},
	{"qrcode", "qrcode barcode code data info information matrix qr qr-code"},
	{"fingerprint", "fingerprint authentication biometric fingerprint id identification lock privacy security"},
	{"wifi", "wifi access point connection connectivity hotspot internet network online router"},
	{"server", "server backend cloud computer cpu data center database hardware hosting"},
	{"hard-drive", "hard drive backup computer data device disk drive hard disk hard drive"},
	{"microchip", "microchip chip circuit computer cpu device electronic hardware microprocessor"},
	{"memory", "memory DIMM RAM chip computer hardware memory memory card memory module"},
	{"bezier-curve", "bezier curve anchor points bezier control points curve drawing graphic design illustration line"},
	{"infinity", "infinity continuous endless eternity forever infinite infinity loop math"},
	{"hourglass", "hourglass countdown hourglass hourglass not done loading minute sand stopwatch time"},
	{"stopwatch", "stopwatch chronometer clock countdown stopwatch stopwatch clock stopwatch device stopwatch icon stopwatch measurement"},
	{"bullseye", "bullseye aim archery bullseye dartboard focus goal objective precision"},
	{"crosshairs", "crosshairs GPS aim bullseye center crosshair focus location marker"},
	{"rocket", "rocket astronaut booster exploration flight launch missile nasa orbit"},
	{"anchor", "anchor anchor berth boat dock embed harbor link maritime"},
	{"mountain", "mountain climbing glacier hiking hill landscape mountain nature outdoor"},
	{"water", "water aqua drop fluid hydration lake liquid ocean refreshment"},
	{"spa", "spa aromatherapy calm flora health lotus massage mindfulness plant"},
	{"paw", "paw animal cat claw dog footprint mammal paw paw pad"},
	{"dog", "dog animal bark canine companion dog domestic animal mammal pet"},
	{"cat", "cat animal cat claw cute domestic feline fur kitten"},
	{"fish", "fish Pisces animal aquarium aquatic fish fishing goldfish marine"},
	{"kiwi-bird", "kiwi bird animal bird birdwatching endangered fauna flightless kiwi native"},
	{"burger", "burger beef bun burger cheeseburger dinner fast food food grill"},
	{"pizza-slice", "pizza slice cheese chicago dinner fast food food italian lunch mozzarella"},
	{"wine-glass", "wine glass alcohol bar beverage cabernet celebration cocktail drink glass"},
	{"cake-candles", "cake candles anniversary bakery birthday blow out candles cake candles celebration dessert"},
	{"gift", "gift birthday box celebration christmas festive generosity gift giving"},
	{"gamepad", "gamepad arcade console controller d-pad game controller gamepad gaming joystick"},
	{"dice", "dice board game chance cube dice dice game die gambling game"},
	{"football", "football american football ball field football game gridiron helmet nfl"},
	{"trophy", "trophy achievement award champion competition cup honor prize reward"},
	{"medal", "medal achievement award badge bronze medal champion gold medal honor medal"},
}
